### ISSUE TITLE
Can't open first blog post on Netlify CMS

### ISSUE THREAD

**Issue by Hoodlum-Z** [remarkjs/remark#411] opened 2019-06-25 17:53 UTC
I'm trying to open the first blog post on the Gatsby starter site template using the Netlify CMS and get an error. It's telling me to report it.

**Error

There's been an error - please report it.

Details

1:1: Incorrectly eaten value: please report this warning on  http://git.io/vg5Ft**

Operating system: Windows 10 developer build - latest one.

Nothing to explain really other than the link didn't work. Thanks.

**Comment by ChristianMurphy** [comment] 2019-06-25 18:10
@Hoodlum-Z which starter are you using?

**Comment by wooorm** [comment] 2019-06-25 18:22
Probably an issue with one of the gatsby plugins your starter is using.
remark it self almost never causes this, but gatsby plugins are know to sometimes cause it.

**Comment by Hoodlum-Z** [comment] 2019-06-25 18:37
@ChristianMurphy just the Kaldi coffee template for Gatsby.

@wooorm Thanks for the advice!

**Comment by ChristianMurphy** [comment] 2019-06-25 18:44
https://github.com/netlify-templates/gatsby-starter-netlify-cms ?

**Comment by Hoodlum-Z** [comment] 2019-06-25 18:48
Yes, that is the same website.

**Comment by ChristianMurphy** [comment] 2019-06-25 19:09
I cloned the repo at commit https://github.com/netlify-templates/gatsby-starter-netlify-cms/tree/70ea9ca8f4df9305c6c0d2a8b6faa8dbae8d200e

on `yarn start`, an ESLint issue, but no Remark issue

```
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: VariableDeclarator ASTNodes are not handled by markPropTypesAsUsed
Occurred while linting ~/test/gatsby-starter-netlify-cms/src/components/PreviewCompatibleImage.js:7
    at markPropTypesAsUsed (~/test/gatsby-starter-netlify-cms/node_modules/eslint-plugin-react/lib/util/usedPropTypes.js:338:15)
    at Object.VariableDeclarator
(~/test/gatsby-starter-netlify-cms/node_modules/eslint-plugin-react/lib/util/usedPropTypes.js:492:9)
    at updatedRuleInstructions.<computed>
(~/test/gatsby-starter-netlify-cms/node_modules/eslint-plugin-react/lib/util/Components.js:780:47)
    at ~/test/gatsby-starter-netlify-cms/node_modules/eslint/lib/util/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (~/test/gatsby-starter-netlify-cms/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector
(~/test/gatsby-starter-netlify-cms/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors
(~/test/gatsby-starter-netlify-cms/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode
(~/test/gatsby-starter-netlify-cms/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode
(~/test/gatsby-starter-netlify-cms/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
```

And no issues running `yarn build` and `yarn serve`.

---

Cannot reproduce this issue with the given details.
Closing for now.

**Closed by ChristianMurphy** 2019-06-25 19:09 UTC

**Comment by Hoodlum-Z** [comment] 2019-06-25 19:22
Okay thanks for your help. Just in case anyone else has a similar issue, I did use the same template as you, but I used the one-click install from Netlify and also used NPM rather than Yarn. 

Not sure if that would make a difference, but possibly?

**Comment by ChristianMurphy** [comment] 2019-06-25 19:28
For Yarn I tested with:

```
$ node --version
v12.4.0
$ yarn --version
1.16.0
$ lsb_release -a
Ubuntu 18.04.2 LTS
```

---

> I used the one-click install from Netlify and also used NPM rather than Yarn.

Retested with `npm`

```
$ node --version
v12.4.0
$ npm --version
6.9.0
$ lsb_release -a
Ubuntu 18.04.2 LTS
```

I got the same results as with Yarn.

---

Do you see the issue if you run `npm start` or `npm run build && npm run serve` locally?
Or only within the Netlify Admin Console?

**Comment by wooorm** [comment] 2019-06-25 19:28
Again, sounds like a bug with netlify or the starter, best to raise it there, with the markdown you're using

**Comment by Hoodlum-Z** [comment] 2019-06-25 19:38
Yes, it seems like a problem with the Netlify CMS software. For whatever reason they said post the error here, but I'll see if I can contact them directly instead.
