### ISSUE TITLE
Incorrect markdown to html italic + bold+italic + italic

### ISSUE THREAD

**Issue by fabriqbruno** [remarkjs/remark#1324] opened 2024-04-29 21:50 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Link to runnable example

```ts
import rehypeStringify from "rehype-stringify";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import { unified } from "unified";

export const markdownToHtml = (markdown: string) => {
  const result = unified().use(remarkParse).use(remarkRehype).use(rehypeStringify).processSync(markdown);
  return result.toString();
};
```

### Steps to reproduce

convert `*i****b****i*` to html

Node 20.12.2

### Expected behavior

output: *i****b****i*

https://spec.commonmark.org/dingus/?text=*i****b****i*

### Actual behavior

output: *i****b******i*

### Package manager

npm 8

### OS

Windows

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment] 2024-04-29 22:54
Duplicate of https://github.com/micromark/micromark/issues/162

**Closed by ChristianMurphy** 2024-04-29 22:54 UTC
Labels: 👯 no/duplicate, 🤞 phase/open
