### ISSUE TITLE
wrong h3 indentation after bullet point

### ISSUE THREAD

**Issue by wischi-chr** [remarkjs/remark#325] opened 2018-02-11 13:49 UTC
The following markdown is not rendered correctly

```
# Indentation Test

### Header 1
  - Bulletpoint 1
### Header 2 <---
  - Bulletpoint 2
```

On github it looks like this: https://gist.github.com/wischi-chr/dc48d7957e80fb4e2024f7f304489ced
![correct_markdown](https://i.imgur.com/dciJDNV.png)

but it's rendered like that:

![wrong_markdown](https://i.imgur.com/Qfi11b2.png)

**Comment by ChristianMurphy** [comment] 2018-07-24 01:32
Looks alright in AST Explorer http://astexplorer.net/#/gist/6e039bf0107be39caa82bef68a6d8c02/00b0474f8ca4f6c1179ac55015094806e1528cf6
What are you using to render @wischi-chr?

**Comment by wooorm** [comment] 2018-08-19 11:31
Duplicate of https://github.com/remarkjs/remark/pull/319

**Closed by wooorm** 2018-08-19 11:31 UTC
Labels: question
