### ISSUE TITLE
Source position property not available for some autolinks

### ISSUE THREAD

**Issue by enriquecastl** [remarkjs/remark#1001] opened 2022-06-08 13:18 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-parse, remark-gfm

### Link to runnable example

https://codesandbox.io/s/reverent-mclean-rihnmh?file=/src/index.js

### Steps to reproduce

- Parse the following autolink using remark and the remark-gfm plugin `[https://example.com>`
- You should obtain an MDAST tree that lacks source position information for the links and the text surrounding the link.

Runtime: Chrome web browser
Package manager: yarn

### Expected behavior

The link node and the text nodes surrounding the link have proper source position information.

### Actual behavior

The link node and the text nodes surrounding the link lack source position information.

### Package manager

Other (please specify in steps to reproduce)

### OS

macOS

### Build and bundle tools

Webpack

**Comment by ChristianMurphy** [comment] 2022-06-08 13:23
Duplicate of https://github.com/remarkjs/remark-gfm/issues/16

**Closed by ChristianMurphy** 2022-06-08 13:23 UTC
Labels: 🤞 phase/open
