### ISSUE TITLE
remark-parse: `(` in strong block will broke the block

### ISSUE THREAD

**Issue by ZxBing0066** [remarkjs/remark#1207] opened 2023-08-13 14:05 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-parse: ^9|^10

### Steps to reproduce

https://codesandbox.io/s/remark-parser-strong-bug-1-yggwkm?file=/src/styles.css

`**aaa(**123` will be parse to a paragraph without children which should be a paragraph with a strong children.

![image](https://github.com/remarkjs/remark/assets/5652404/12325ab8-17cc-4673-9cf0-3495b7881c0c)

### Expected behavior

It should be a strong block, this is broken with version 9 or 10, but works fine with version 8.

https://codesandbox.io/s/remark-parser-strong-bug-2-tlc8dd?file=/src/styles.css

![image](https://github.com/remarkjs/remark/assets/5652404/600c3ba8-2d11-42aa-8489-7adb1bf16062)

### Actual behavior

![image](https://github.com/remarkjs/remark/assets/5652404/dafc90b9-4f43-42ac-9171-4f316b994580)

**Comment by ChristianMurphy** [comment] 2023-08-13 14:27
Welcome @ZxBing0066! 👋 

This is a duplicate of https://github.com/remarkjs/remark/issues/917

To quote the answer from there

> > A left-flanking delimiter run is a delimiter run that is (1) not followed by Unicode whitespace, and either (2a) not followed by a Unicode punctuation character, or (2b) followed by a Unicode punctuation character and preceded by Unicode whitespace or a Unicode punctuation character. For purposes of this definition, the beginning and the end of the line count as Unicode whitespace.
>
> And closing strong text
>
> > A right-flanking delimiter run is a delimiter run that is (1) not preceded by Unicode whitespace, and either (2a) not preceded by a Unicode punctuation character, or (2b) preceded by a Unicode punctuation character and followed by Unicode whitespace or a Unicode punctuation character. For purposes of this definition, the beginning and the end of the line count as Unicode whitespace.
>
> (https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis)
>
> Don't seem to be met.
>
> I'm not sure the HTML `1<strong>(abc)</strong>2` can be represented precisely/exactly in markdown.
>
> A close equivalent may be adding zero width space characters between `1` and `**` as well as `**` and `2`. 🤔 


To answer your other comment

> It should be a strong block, this is broken with version 9 or 10, but works fine with version 8.

`remark` 8 had a bug not implementing CommonMark correctly, that has been addressed in later versions and will remain fixed.

**Closed by ChristianMurphy** 2023-08-13 14:27 UTC
Labels: 🤞 phase/open

**Comment by ZxBing0066** [comment] 2023-08-14 13:57
Hi @ChristianMurphy, 

Thanks for you response, that's very helpful. However the current behavior still makes me confusing. If that is by design, I think `**aaa\(**123` should be working since the punctuation character has been escaped. Just my own option.

**Comment by ChristianMurphy** [comment] 2023-08-14 14:10
In CommonMark `**aaa\(**123` is not strong text either https://spec.commonmark.org/dingus/?text=**aaa%5C(**123
same in GitHub Flavored Markdown (GFM), `**aaa\(**123` renders as **aaa\(**123

**Comment by ZxBing0066** [comment] 2023-08-15 13:27
> 

OK, you are right. Thanks for your patient answer~😌
