### ISSUE TITLE
Problem with strong when using pedantic.

### ISSUE THREAD

**Issue by richtera** [remarkjs/remark#404] opened 2019-05-17 13:40 UTC
https://github.com/remarkjs/remark/blob/cca8385746c2f3489b2d491e91ab8c581901ae8a/packages/remark-parse/lib/tokenize/text.js#L42

When tracing through the above line in pedantic mode it seems to me the from index should be 2 because when using "strong" and "emphasis" the locator will return "*" for the second asterisk inside of the "**some text**" as a location and will adjust the minimum. Then it will try to run the "emphasis" tokenizer which bails out and leaves "**" inside of the text.

This also shows up in this defect as well:
https://github.com/gatsbyjs/gatsby/issues/5417

Does that make sense or am I missing something?

**Comment by ChristianMurphy** [comment] 2019-05-25 01:59
@richtera could you provide a sample of markdown where the AST parses unexpectedly? and what the expected output would be?

**Comment by wooorm** [comment] 2019-05-25 08:01
From gatsbyjs/gatsby#5417, the problem seems to be that in `alp_ha bra_vo`, `ha bra` is emphasises in pedantic mode. This is a “feature” of pedantic mode. CM / GFM do not have this feature.

The issue you post here seems to be something else? In that case, see Christian’s comment.

**Comment by richtera** [comment] 2019-05-25 13:10
My problem is that something with `__` is not recognized because `_` is found as the second `_` within the set of `__` so `__something strong__` never triggers as strong but rather an empty em.

**Comment by wooorm** [comment] 2019-05-25 13:52
Could you post more expansive example? This works for me.

**Comment by richtera** [comment] 2019-05-25 14:14
Interesting, then I might have something external to remark itself that makes this fail. I didn't think I had any weird plugins. Looks like I need to dig deeper then. Some of my authors are also using a long sequence of `_` without escapes to put like a fill in the blank space which could have some additional side effects. I will do more debugging.

**Comment by wooorm** [comment] 2019-05-25 14:18
I’ve been working on better docs for [getting support](https://github.com/syntax-tree/.github/blob/master/support.md) and for [contributing](https://github.com/syntax-tree/.github/blob/master/contributing.md). Currently in a separate org of the ecosystem, in the future here as well. Maybe it’ll help you.

I’ll close this now because it’s unclear what the issue is. But if you find something actionable and broken, e.g., please open a new issue!

**Closed by wooorm** 2019-05-25 14:18 UTC
