### ISSUE TITLE
🚀 Support Github-style Alerts, Callouts, etc. (Beta)

### ISSUE THREAD

**Issue by jon-sully** [remarkjs/remark#1280] opened 2024-01-20 14:25 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Github recently implemented a very neat feature for adding various tagged callouts to GFM. I'd love to use this in my various projects internally relying on Remark! Typora (the application I actually write most of my content in) also recently [added support](https://support.typora.io/What's-New-1.8/), though I'm not sure which markdown engine they're running 

https://github.com/orgs/community/discussions/16925

### Solution

Not exactly sure the implementation here, but the discussion link over on the GFM side illustrates the intended outcome well! 

### Alternatives

It's not currently implemented, so I suppose the alternative is to just not do this 😉😜

**Comment by JounQin** [comment] 2024-01-20 14:30
Duplicate of https://github.com/remarkjs/remark-gfm/issues/53

**Closed by JounQin** 2024-01-20 14:30 UTC
Labels: 🤞 phase/open

**Comment by jon-sully** [comment] 2024-01-20 14:45
D'oh! Apologies!

**Comment by jon-sully** [comment] 2024-01-20 14:48
Note for others — this got implemented as a Rehype plugin. See https://github.com/chrisweb/rehype-github-alerts

**Comment by LuudJanssen** [comment] 2024-03-03 23:29
I also created a Remark plugin to transform GitHub's syntax to the directives syntax: [remark-github-admonitions-to-directives](https://github.com/incentro-dc/remark-github-admonitions-to-directives)

**Comment by wooorm** [comment] 2024-03-04 10:47
I strongly recommend making rehype plugins, rehype works on HTML, GH does this on HTML!

**Comment by LuudJanssen** [comment] 2024-03-04 11:10
@wooorm I understand, but my plugin doesn't produce HTML on purpose so existing tools using the directives syntax (like Docusaurus and the admonitions plugin) can be reused. It just converts MD syntax A to MD syntax B.

**Comment by wooorm** [comment] 2024-03-04 11:12
ahh right, sorry, missed the last part!
