### ISSUE TITLE
Mis-parsing with HTML comments

### ISSUE THREAD

**Issue by james-atkins** [remarkjs/remark#317] opened 2017-12-27 23:16 UTC
remark fails to parse markdown containing Google Charts JavaScript; in particular, the problem seems to be caused by HTML comments. 

See [AST Explorer](https://astexplorer.net/#/gist/d86c2de34250913b6eb1d46ce5fd06c9/c5d1958010a4d26d15d023a19ac1ef27f2fde10f) for a working example. The first `script` tag is not parsed as HTML, but instead its contents are erroneously parsed separately as paragraphs etc.

However if a newline is entered between lines 4 and 5 then everything is successfully parsed.

### Your environment

remark-8.0.0
Firefox 57.0.1

**Comment by wooorm** [comment] 2017-12-28 12:02
“fails” is a pretty big word 😉 This probably is the way it’s supposed to be.

1. Have you checked with other markdown vendors, to see if they differ?
2. Why are you passing HTML (and JS) to remark? 🤔

**Comment by wooorm** [comment] 2018-01-17 15:27
Hey, I’m closing this for now because I perceive this as “a feature, not a bug”, but feel free to ping and answer my previous questions and I’ll re-open this!

**Closed by wooorm** 2018-01-17 15:27 UTC
